# Generated by Django 4.1.5 on 2023-10-23 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.TextField(max_length=100)),
                ('plaque', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=20, unique=True)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('sujet', models.CharField(max_length=150)),
                ('message', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PayeAgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('service', models.CharField(choices=[('Voyage', 'voyage'), ('Bagage', 'Bagade')], max_length=11)),
                ('destination', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PayeBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('service', models.CharField(choices=[('Voyage', 'voyage'), ('Bagage', 'Bagade')], max_length=11)),
                ('destination', models.CharField(max_length=100)),
                ('banque', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PayeTel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('service', models.CharField(choices=[('Voyage', 'voyage'), ('Bagage', 'Bagade')], max_length=11)),
                ('destination', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_depart', models.CharField(max_length=200)),
                ('ville_arrive', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Voyage', 'voyages'), ('Bagage', 'Bagages')], max_length=32)),
                ('date', models.DateTimeField(verbose_name='date du jour')),
                ('nom', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('details', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chauffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('matricule', models.CharField(max_length=200)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.camion')),
            ],
        ),
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('chauffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.chauffer')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.reservation')),
            ],
        ),
    ]
